### ISSUE TITLE
Python tool

### ISSUE THREAD

**Issue by medwatt** [bmurmann/Book-on-gm-ID-design#1]
Hello. I was reading your book and didn't have access to matlab. So, I created a similar tool but in python. It supports both ngspice and hspice. Here is the repo in case someone else is reading this book and doesn't have access to matlab: https://github.com/medwatt/gmid.

**Comment by bmurmann** [comment]
Excellent, thank you!

**Comment by avlsi** [comment]
I would like to bring some attention to this repository also.
https://github.com/dreoilin/pygmid/tree/main

**Comment by ZeRuiCustodio** [comment]
Hello! Just to say that I have managed to use dreoilin pygmid repository successfully! 😊 Best regards!
